sonar.projectKey=VexBor_Lecturers_work
sonar.working.directory=C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work
sonar.pullrequest.cache.basepath=C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work

96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.projectKey=VexBor_Lecturers_work:96AC540C-C538-4341-B3F6-81D17F9D13AC
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.projectName=Lecturers_work
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.projectBaseDir=C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.sourceEncoding=utf-8
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.tests=
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.sources=\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Application\\Services\\AuthService.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Application\\Services\\StudyService.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Core\\Entities\\Course.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Core\\Entities\\Record.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Core\\Entities\\User.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Core\\Interface\\IEntity.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Core\\Interface\\IRepository.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Infrastructure\\Data\\CourseRepository.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Infrastructure\\Data\\CsvRepositoryBase.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Infrastructure\\Data\\RecordRepository.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Infrastructure\\Data\\UserRepository.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\Program.cs",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\.editorconfic",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\courses.csv",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\records.csv",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\stylecop.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\users.csv",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\obj\\Lecturers_work.csproj.nuget.dgspec.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\obj\\project.assets.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\obj\\project.packagespec.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\bin\\Debug\\net8.0\\Lecturers_work.deps.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\bin\\Debug\\net8.0\\Lecturers_work.runtimeconfig.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\bin\\Debug\\net9.0\\Lecturers_work.deps.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\bin\\Debug\\net9.0\\Lecturers_work.runtimeconfig.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\obj\\Debug\\net8.0\\Lecturers_work.sourcelink.json",\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\obj\\Debug\\net9.0\\Lecturers_work.sourcelink.json"

96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\.sonarqube\\out\\0"
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\.sonarqube\\out\\0\\Issues.json"
96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.cs.scanner.telemetry=\
"C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\.sonarqube\\out\\0\\Telemetry.json"

96AC540C-C538-4341-B3F6-81D17F9D13AC.sonar.working.directory=C:\\Users\\vadim\\Documents\\OPAM\\Lecturers_work\\Lecturers_work\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=https://sonarcloud.io
sonar.organization=vexbor
sonar.visualstudio.enable=false

sonar.modules=96AC540C-C538-4341-B3F6-81D17F9D13AC

